export const SET_PROFILE = "SET_PROFILE";
export const ADD_SONG_TO_FAVOURITE = "ADD_SONG_TO_FAVOURITE";
export const REMOVE_SONG_FROM_FAVOURITE = "REMOVE_SONG_FROM_FAVOURITE";

export const ADD_SONG_TO_BASKET = "ADD_SONG_TO_BASKET";
export const REMOVE_SONG_FROM_BASKET = "REMOVE_SONG_FROM_BASKET";
